### PR TITLE
WIP: deis -> hephy in README and groovy

### PR DESCRIPTION
**Pull request by kingdonb**
* use 'teamhephy' github org
* quay.io/deisci becomes quay.io/kingdonb for now
* deis.com -> teamhephy.com and deis-com -> teamhephy-com
* deisthree -> teamhephy
* in some places  deis -> hephy

DOCKER_USERNAME', 'hephybot', 'Docker Hub account name'
DOCKER_EMAIL', 'dummy-address@teamhephy.com', 'Docker Hub email address'
QUAY_USERNAME', 'teamhephy+jenkins', 'Quay account name'
QUAY_EMAIL', 'XXXXXXXX@teamhephy.com', 'Quay email address'

* These may change, probably not considered stable before 2/22/2018
* (maybe even til) 3/15/2018 - plan teamhephy.com website release date

- [ ] deis.io -> teamhephy.info
- [ ] charts.teamhephy.com

* hope to have e2e validating Deis from teamhephy repos by 2/25/2018

### CODE REVIEW

**Comment by kingdonb** [comment]
This is basically working now, it generates 120 jobs and ends with Blue/(SUCCESS), but there are a lot of credentials and things that need to be added so the jobs it generates will fire, and trigger properly against github hooks.  And then someone has to figure out what each of these jobs does, as well as when and whether any of them require any manual intervention.

**Comment by Cryptophobia** [comment]
Thank you for taking the look into this. Should we hold off on merging this before we finalize dockerhub accounts and a permanent testing cluster?

**Comment by kingdonb** [comment]
Yes, I want to get all of the jenkins jobs working, signatory, etc.  Some of the strings will still probably need to change again before merge, and since I'm the one who is running Jenkins, it's not a problem for me to set seed-jobs to run out of my personal github fork.

But as I'm putting the pieces together, I'm forking teamhephy repos in a number of places in order to change strings in other repos to also point at my own personal fork, and much of that is additional work that likely won't be changes we're going to want to merge after I've proven that we can build and e2e the whole stack.

I just want to merge everything together (simultaneously) at once when it's ready, and keep to doing that as much as possible.  I'm still a novice at GitHub teams.

**Comment by kingdonb** [comment]
I will take the WIP indicator off of this when the CI stuff has stabilized a bit more

**Comment by Cryptophobia** [comment]
Okay, great! Let's figure out all these pieces together so we can proceed with the first release!

**Comment by kingdonb** [comment]
The missing piece was workflow-manager-api, which is public now

Very soon I will have a full mirror of deis v2.18 charts and the "versions" service in place which feeds into CI to help Jenkins distinguish PR builds from release builds and other friends

The versions service is not critical, but appears to be somewhat deeply embedded in the jenkins-jobs.  I am running a build out of yebyen/workflow#2 which will also have some patches coming for the release, after the remaining parts shake out...

We should be able to install "hephy v2.18" which is mostly faithful to deis workflow v2.18.0, from its mirrored home on our new charts server, and test that much sooner than all this will hopefully finally come together, though!

**Comment by Cryptophobia** [comment]
Great work! I can smell the scent of the release brewing!

**Comment by yebyen** [comment]
There are updates in the linked PR yebyen/workflow#2

Things are shaping up!

**Comment by yebyen** [comment]
Closing in favor of #33 which has squashed a bunch of commits, and is also a little bit closer to finished/correct "prod-release ready" version

The quay user "hephyci" is the staging target for builds, quay user "hephy" only receives finished builds.  Look in `jobs/release_candidate_promote.groovy` touched by this patch if you want to know more about what stage of the build puts images into the prod image repo.  I think they are copied from staging at some point that requires a manual step.

(Nobody copies them into prod by hand, it's done by CI)

**Comment by kingdonb** [comment]
Closing for #33

**Pull request closed without merging**
